version: '3'
services:
  cnlunar:
    image: ghcr.io/jymusic0663/cnlunar:latest
    # build: .
    container_name: cnlunar
    hostname: cnlunar
    networks:
      - bridge
    ports:
      - "5000:5000/tcp"
    restart: unless-stopped
